export type Category = 'Sécurité & IA' | 'DevOps & Cloud' | 'Systèmes & Réseau' | 'Web & Backend' | 'Frontend & JS' | 'CLI & Outils' | 'Apps & SaaS'

export interface Project {
  slug: string
  title: string
  repo: string
  lang: string
  description: string
  longDescription: string
  features: string[]
  tags: string[]
  category: Category
  private?: boolean
  liveUrl?: string
}

export const ALL_PROJECTS: Project[] = [
  // ───── Sécurité & IA ─────
  {
    slug: 'secure-shield',
    title: 'Secure-Shield',
    repo: 'Secure-Shield',
    lang: 'TypeScript',
    description: 'Plateforme SOC avec agent IA pour la détection et réponse aux incidents en temps réel.',
    longDescription: 'Secure-Shield est une plateforme Security Operations Center (SOC) de nouvelle génération intégrant un agent IA autonome. Le système analyse en continu les logs système, les flux réseau et les événements de sécurité pour détecter les anomalies, qualifier les incidents et déclencher des réponses automatisées. L\'agent IA utilise des modèles de langage pour corréler les alertes et réduire les faux positifs.',
    features: [
      'Agent IA autonome pour la détection d\'anomalies et qualification d\'incidents',
      'Dashboard SOC en temps réel avec visualisation des alertes',
      'Corrélation automatique des événements multi-sources',
      'Réponse aux incidents automatisée avec playbooks configurables',
      'Intégration avec les outils SIEM standards',
    ],
    tags: ['TypeScript', 'AI Agent', 'SOC', 'Security', 'Real-time'],
    category: 'Sécurité & IA',
  },

  // ───── DevOps & Cloud ─────
  {
    slug: 'cloud-design',
    title: 'Cloud-Design',
    repo: 'Cloud-Design',
    lang: 'Terraform',
    description: 'Infrastructure microservices déployée sur AWS avec Terraform et ECS.',
    longDescription: 'Cloud-Design est une infrastructure as code complète pour déployer une architecture microservices sur AWS. Le projet définit l\'ensemble de l\'infrastructure cloud — VPC, subnets, security groups, load balancers, ECS clusters et task definitions — via des modules Terraform réutilisables. L\'objectif est d\'obtenir une infrastructure reproducible, versionnée et auditable.',
    features: [
      'Infrastructure AWS complète définie en Terraform (VPC, ECS, ALB)',
      'Modules Terraform réutilisables et paramétrables',
      'Auto-scaling des services ECS selon la charge',
      'Gestion des secrets via AWS Secrets Manager',
      'Monitoring et alerting avec CloudWatch',
    ],
    tags: ['Terraform', 'AWS', 'ECS', 'Microservices', 'IaC'],
    category: 'DevOps & Cloud',
  },
  {
    slug: 'code-keeper',
    title: 'Code-Keeper',
    repo: 'Code-Keeper',
    lang: 'Terraform',
    description: 'Pipeline CI/CD complet pour microservices avec GitLab CI et Terraform.',
    longDescription: 'Code-Keeper implémente un pipeline CI/CD de bout en bout pour une architecture microservices. Chaque push déclenche une chaîne automatisée : tests unitaires et d\'intégration, analyse de qualité de code, build Docker, scan de vulnérabilités, déploiement en staging puis production via Terraform. Le pipeline garantit zéro downtime avec des déploiements blue/green.',
    features: [
      'Pipeline CI/CD multi-stages avec GitLab CI',
      'Déploiement blue/green pour zéro downtime',
      'Scan de vulnérabilités Docker avec Trivy',
      'Promotion automatique staging → production avec gates d\'approbation',
      'Rollback automatique en cas d\'échec des health checks',
    ],
    tags: ['CI/CD', 'GitLab', 'Terraform', 'DevOps', 'Docker'],
    category: 'DevOps & Cloud',
  },
  {
    slug: 'orchestrator',
    title: 'Orchestrator',
    repo: 'orchestrator',
    lang: 'Python',
    description: 'Déploiement de microservices Kubernetes avec K3s et automatisation complète.',
    longDescription: 'Orchestrator est un système de déploiement automatisé pour microservices sur Kubernetes léger (K3s). Le projet gère le provisioning des nœuds, l\'installation de K3s, le déploiement des services via Helm charts et la configuration des ingress controllers. Un CLI Python permet de gérer l\'ensemble du cycle de vie des applications déployées.',
    features: [
      'Provisioning automatisé de clusters K3s multi-nœuds',
      'Déploiement de microservices via Helm charts',
      'CLI Python pour la gestion du cycle de vie',
      'Configuration automatique des ingress NGINX',
      'Health checks et restart policies configurables',
    ],
    tags: ['Kubernetes', 'K3s', 'Python', 'Helm', 'Microservices'],
    category: 'DevOps & Cloud',
  },
  {
    slug: 'distributed-media-platform',
    title: 'Distributed Media Platform',
    repo: 'Distributed-realtime-media-plateform',
    lang: 'Makefile',
    description: 'Plateforme média distribuée temps réel avec architecture scalable multi-nœuds.',
    longDescription: 'Plateforme de diffusion média distribuée conçue pour gérer des flux temps réel à grande échelle. L\'architecture multi-nœuds repose sur un système de coordination distribué permettant la réplication des données, la tolérance aux pannes et l\'équilibrage de charge dynamique. Le projet explore les problématiques de consensus distribué et de cohérence éventuelle.',
    features: [
      'Architecture distribuée multi-nœuds avec tolérance aux pannes',
      'Diffusion temps réel avec latence minimisée',
      'Système de coordination et consensus distribué',
      'Équilibrage de charge dynamique entre les nœuds',
      'Conteneurisation complète avec Docker Compose',
    ],
    tags: ['Distributed Systems', 'Real-time', 'Media', 'Docker', 'Streaming'],
    category: 'DevOps & Cloud',
  },

  // ───── Systèmes & Réseau — Rust ─────
  {
    slug: 'multiplayer-fps',
    title: 'Multiplayer FPS',
    repo: 'multiplayer-fps',
    lang: 'Rust',
    description: 'Jeu FPS multijoueur en réseau avec Bevy Engine, prédiction de mouvement et netcode optimisé.',
    longDescription: 'Jeu de tir à la première personne multijoueur développé en Rust avec le moteur Bevy. Le projet résout les problèmes classiques du netcode : latence réseau, désynchronisation et triche. L\'architecture client-serveur implémente la prédiction côté client et la réconciliation serveur pour une expérience fluide même avec de la latence. Le protocole UDP custom minimise l\'overhead réseau.',
    features: [
      'Moteur de jeu Bevy avec rendu 3D et physique',
      'Prédiction côté client et réconciliation serveur',
      'Protocole UDP custom pour minimiser la latence',
      'Interpolation des entités distantes pour fluidité visuelle',
      'Serveur dédié headless avec tick rate configurable',
    ],
    tags: ['Rust', 'Bevy', 'Netcode', 'UDP', 'Game', '3D'],
    category: 'Systèmes & Réseau',
  },
  {
    slug: 'localhost',
    title: 'Localhost',
    repo: 'localhost',
    lang: 'Rust',
    description: 'Serveur HTTP from scratch en Rust avec gestion des routes, méthodes et fichiers statiques.',
    longDescription: 'Implémentation d\'un serveur HTTP/1.1 complet en Rust sans librairie externe. Le projet couvre l\'intégralité du protocole : parsing des requêtes, routing, gestion des méthodes GET/POST/DELETE, serving de fichiers statiques, chunked encoding et gestion des connexions persistantes (keep-alive). Développé avec une attention particulière à la gestion mémoire et aux performances.',
    features: [
      'Parsing HTTP/1.1 complet from scratch',
      'Routing basé sur des expressions régulières',
      'Serving de fichiers statiques avec MIME types',
      'Gestion des connexions keep-alive et chunked encoding',
      'Gestion concurrente des connexions avec thread pool',
    ],
    tags: ['Rust', 'HTTP', 'Server', 'Systems', 'Protocol'],
    category: 'Systèmes & Réseau',
  },
  {
    slug: 'wget',
    title: 'Wget',
    repo: 'wget',
    lang: 'Rust',
    description: 'Réimplémentation de wget en Rust : téléchargement concurrent, progress bar et miroir de site.',
    longDescription: 'Réimplémentation fidèle de l\'outil GNU wget en Rust. Le projet supporte le téléchargement de fichiers via HTTP/HTTPS, le mirroring récursif de sites web, la reprise de téléchargements interrompus et les téléchargements en arrière-plan. Une progress bar en temps réel affiche la vitesse et l\'ETA. Le parsing HTML permet de suivre les liens pour le mirroring.',
    features: [
      'Téléchargement HTTP/HTTPS avec reprise sur interruption',
      'Mirroring récursif de sites web avec parsing HTML',
      'Progress bar temps réel avec vitesse et ETA',
      'Téléchargements multiples concurrents en background',
      'Respect du fichier robots.txt et rate limiting',
    ],
    tags: ['Rust', 'CLI', 'HTTP', 'Networking', 'Concurrency'],
    category: 'Systèmes & Réseau',
  },
  {
    slug: 'smart-road',
    title: 'Smart Road',
    repo: 'smart-road',
    lang: 'Rust',
    description: 'Simulation de trafic routier avec algorithme de gestion d\'intersections sans collisions.',
    longDescription: 'Simulation graphique d\'une intersection routière intelligente en Rust. Le projet implémente un algorithme de contrôle de trafic garantissant l\'absence de collisions tout en maximisant le débit. Les véhicules sont simulés avec des comportements réalistes (accélération, freinage, changement de voie) et l\'algorithme adapte dynamiquement les priorités selon la densité du trafic.',
    features: [
      'Rendu graphique 2D temps réel de l\'intersection',
      'Algorithme de contrôle sans collision avec priorités dynamiques',
      'Simulation physique des véhicules (accélération, freinage)',
      'Statistiques de débit et temps d\'attente en temps réel',
      'Paramétrage de la densité et des comportements de trafic',
    ],
    tags: ['Rust', 'Simulation', 'Algorithm', 'Graphics', 'SDL2'],
    category: 'Systèmes & Réseau',
  },

  // ───── Web & Backend — Go ─────
  {
    slug: 'real-time-forum',
    title: 'Real-Time Forum',
    repo: 'real-time-forum',
    lang: 'Go',
    description: 'Forum complet avec messagerie instantanée via WebSocket, authentification JWT et SQLite.',
    longDescription: 'Application de forum full stack développée en Go avec une interface Single Page Application. La messagerie privée en temps réel repose sur WebSocket avec une gestion robuste des déconnexions et reconnexions. Le backend expose une API REST complète avec authentification JWT, gestion des sessions et stockage SQLite optimisé avec indexation.',
    features: [
      'Messagerie instantanée temps réel via WebSocket',
      'Authentification JWT avec refresh tokens',
      'Interface SPA en vanilla JS sans framework',
      'Fil de posts, commentaires et système de likes',
      'Notifications en temps réel pour les nouveaux messages',
    ],
    tags: ['Go', 'WebSocket', 'JWT', 'SQLite', 'SPA', 'Real-time'],
    category: 'Web & Backend',
  },
  {
    slug: 'forum-security',
    title: 'Forum Sécurisé',
    repo: 'forum-security',
    lang: 'Go',
    description: 'Forum avec protections CSRF, XSS, rate limiting et audit de sécurité OWASP.',
    longDescription: 'Extension de sécurité pour forum web implémentant les protections recommandées par l\'OWASP Top 10. Le projet ajoute une couche de défense complète : tokens CSRF pour chaque formulaire, échappement systématique contre XSS, rate limiting par IP et par utilisateur, hachage bcrypt des mots de passe et headers de sécurité HTTP (CSP, HSTS, X-Frame-Options).',
    features: [
      'Protection CSRF avec tokens synchronisés par session',
      'Échappement XSS systématique en entrée et en sortie',
      'Rate limiting par IP avec backoff exponentiel',
      'Headers de sécurité HTTP (CSP, HSTS, X-Frame-Options)',
      'Audit de sécurité OWASP Top 10 complet',
    ],
    tags: ['Go', 'Security', 'CSRF', 'XSS', 'OWASP', 'bcrypt'],
    category: 'Web & Backend',
  },
  {
    slug: 'forum-authentication',
    title: 'Forum Auth',
    repo: 'forum-authentication',
    lang: 'Go',
    description: 'Système d\'authentification OAuth2 (Google/GitHub) avec sessions sécurisées et cookies chiffrés.',
    longDescription: 'Système d\'authentification multi-provider pour application web Go. Le module implémente le flux OAuth2 complet pour Google et GitHub, avec création automatique de compte à la première connexion. Les sessions sont stockées en base de données avec cookies httpOnly/Secure chiffrés. Le module est conçu pour être découplé et réutilisable dans d\'autres projets Go.',
    features: [
      'OAuth2 complet pour Google et GitHub',
      'Sessions persistantes avec cookies httpOnly/Secure',
      'Création automatique de compte à la première connexion',
      'Révocation de session et déconnexion multi-device',
      'Module découplé et réutilisable',
    ],
    tags: ['Go', 'OAuth2', 'Sessions', 'Google', 'GitHub', 'Cookies'],
    category: 'Web & Backend',
  },
  {
    slug: 'net-cat',
    title: 'Net-Cat',
    repo: 'net-cat',
    lang: 'Go',
    description: 'Réimplémentation de NetCat en Go avec chat TCP multicast et gestion des connexions concurrentes.',
    longDescription: 'Réimplémentation de l\'outil NetCat en Go avec des fonctionnalités étendues. L\'outil permet d\'établir des connexions TCP/UDP, de créer des serveurs de chat multicast et de transférer des données entre processus. La gestion des connexions concurrentes repose sur des goroutines et des channels Go pour une architecture non bloquante.',
    features: [
      'Serveur TCP multicast supportant plusieurs clients simultanés',
      'Historique des messages persistent et replay pour nouveaux clients',
      'Nommage des clients et annonces de connexion/déconnexion',
      'Transfert de données binaires via pipe Unix',
      'Gestion propre des déconnexions et nettoyage des ressources',
    ],
    tags: ['Go', 'TCP', 'Networking', 'Goroutines', 'Channels'],
    category: 'Web & Backend',
  },
  {
    slug: 'lem-in',
    title: 'Lem-In',
    repo: 'lem-in',
    lang: 'Go',
    description: 'Simulation de colonies de fourmis sur graphe avec algorithme de flux maximum (BFS/Dijkstra).',
    longDescription: 'Simulation algorithmique du problème de colonies de fourmis : trouver le nombre optimal de chemins disjoints dans un graphe pour acheminer N fourmis de la source au puits en un minimum de tours. Le projet implémente des algorithmes de recherche de chemin (BFS, Dijkstra) et d\'optimisation de flux maximum pour déterminer la stratégie de répartition optimale.',
    features: [
      'Parsing de fichiers de graphe avec validation des erreurs',
      'Algorithme BFS pour la recherche de chemins disjoints',
      'Optimisation du flux maximum (algorithme d\'Edmonds-Karp)',
      'Simulation pas-à-pas avec affichage des mouvements',
      'Visualisation graphique optionnelle de la simulation',
    ],
    tags: ['Go', 'Algorithm', 'Graph', 'BFS', 'Max Flow', 'Simulation'],
    category: 'Web & Backend',
  },

  // ───── Frontend & JavaScript ─────
  {
    slug: 'mini-framework',
    title: 'Mini Framework',
    repo: 'mini-framework',
    lang: 'JavaScript',
    description: 'Framework JavaScript from scratch : DOM virtuel, gestion d\'état réactif, système de routing.',
    longDescription: 'Framework JavaScript minimaliste développé de zéro, inspiré des principes de React et Vue. Le projet implémente les mécaniques fondamentales des frameworks modernes : un Virtual DOM avec algorithme de diffing, un système de réactivité basé sur des Proxies ES6, un router client-side et un mécanisme de composants avec cycle de vie. Le tout en moins de 500 lignes de code.',
    features: [
      'Virtual DOM avec algorithme de diffing performant',
      'Réactivité basée sur Proxy ES6 (type Vue 3)',
      'Router client-side avec historique navigateur',
      'Composants avec cycle de vie (mount, update, unmount)',
      'Système d\'événements et de props typés',
    ],
    tags: ['JavaScript', 'Virtual DOM', 'Framework', 'Proxy', 'Reactive'],
    category: 'Frontend & JS',
  },
  {
    slug: 'bomberman-dom',
    title: 'Bomberman DOM',
    repo: 'bomberman-dom',
    lang: 'JavaScript',
    description: 'Jeu Bomberman multijoueur en JS pur sans canvas, rendu DOM haute performance.',
    longDescription: 'Jeu Bomberman multijoueur développé en JavaScript vanilla, rendu entièrement via manipulation DOM (pas de canvas). Le défi technique est d\'atteindre 60 FPS malgré les manipulations DOM intensives, résolu par batching des updates et minimisation des reflows. Le jeu supporte 2 à 4 joueurs en local avec des niveaux générés procéduralement.',
    features: [
      'Rendu DOM haute performance à 60 FPS sans canvas',
      'Batching des updates DOM pour minimiser les reflows',
      'Multijoueur local 2 à 4 joueurs',
      'Génération procédurale de niveaux',
      'IA basique pour les bots adversaires',
    ],
    tags: ['JavaScript', 'Game', 'DOM', 'Multiplayer', '60FPS'],
    category: 'Frontend & JS',
  },
  {
    slug: 'make-your-game',
    title: 'Make Your Game',
    repo: 'make-your-game',
    lang: 'JavaScript',
    description: 'Jeu 2D optimisé à 60 FPS avec requestAnimationFrame, gestion physique et scores.',
    longDescription: 'Jeu 2D développé en JavaScript avec une contrainte forte de performance : maintenir 60 FPS constants. Le projet explore les techniques d\'optimisation spécifiques aux jeux browser : game loop avec requestAnimationFrame, interpolation temporelle, object pooling pour éviter le garbage collector, et profiling des bottlenecks avec les DevTools Chrome.',
    features: [
      'Game loop optimisée avec requestAnimationFrame',
      'Interpolation temporelle pour découpler logique et rendu',
      'Object pooling pour minimiser le garbage collector',
      'Système de scores avec persistance localStorage',
      'Profiling et optimisation mesurée (DevTools)',
    ],
    tags: ['JavaScript', 'Game', 'Performance', '60FPS', 'Canvas'],
    category: 'Frontend & JS',
  },

  // ───── CLI & Outils — Go ─────
  {
    slug: '0-shell',
    title: '0-Shell',
    repo: '0-shell',
    lang: 'Go',
    description: 'Shell Unix complet en Go avec syscalls bas niveau, gestion processus, signaux et pipes.',
    longDescription: 'Implémentation d\'un shell Unix interactif en Go, couvrant les fonctionnalités essentielles de bash. Le projet manipule directement les syscalls Linux pour la création de processus (fork/exec), la gestion des signaux (SIGINT, SIGTERM, SIGCHLD), les pipes entre processus et la redirection d\'entrée/sortie. L\'éditeur de ligne gère l\'historique et les raccourcis clavier.',
    features: [
      'Création de processus via fork/exec avec syscalls directs',
      'Gestion des signaux Unix (SIGINT, SIGTERM, SIGCHLD)',
      'Pipes entre commandes et redirections I/O',
      'Builtins : cd, ls, pwd, echo, env, export, unset',
      'Historique de commandes et autocomplétion basique',
    ],
    tags: ['Go', 'Shell', 'Syscalls', 'Unix', 'CLI', 'fork/exec'],
    category: 'CLI & Outils',
  },
  {
    slug: 'ascii-art-web',
    title: 'ASCII Art Web',
    repo: 'ascii-art-web-dockerize',
    lang: 'Go',
    description: 'Application web ASCII art containerisée avec Docker, templates Go et interface responsive.',
    longDescription: 'Application web de génération d\'art ASCII développée en Go et déployée via Docker. L\'interface permet de convertir du texte en ASCII art avec différentes polices (shadow, standard, thinkertoy). Le serveur Go utilise html/template pour le rendu serveur-side, et l\'application est containerisée avec Docker pour un déploiement simple et reproductible.',
    features: [
      'Rendu ASCII art avec 3 polices différentes',
      'Serveur Go avec templates html/template',
      'Interface web responsive en HTML/CSS',
      'Containerisation Docker avec image minimaliste',
      'API REST pour la génération programmatique',
    ],
    tags: ['Go', 'Docker', 'Web', 'Templates', 'ASCII Art'],
    category: 'CLI & Outils',
  },
  {
    slug: 'groupie-tracker-geo',
    title: 'Groupie Tracker Geo',
    repo: 'groupie-tracker-geolocalization',
    lang: 'Go',
    description: 'Tracker de concerts musicaux avec géolocalisation, carte interactive et filtres avancés.',
    longDescription: 'Application web de tracking de concerts avec fonctionnalités de géolocalisation. Le projet consomme une API REST externe pour récupérer les données d\'artistes et de concerts, puis les enrichit avec des coordonnées géographiques via geocoding. Une carte interactive (Leaflet.js) affiche les concerts avec clustering des marqueurs. Des filtres avancés permettent de rechercher par artiste, date et lieu.',
    features: [
      'Consommation d\'API REST externe avec caching',
      'Géocodage des adresses en coordonnées GPS',
      'Carte interactive Leaflet.js avec clustering de marqueurs',
      'Filtres dynamiques par artiste, date et localisation',
      'Recherche autocomplete avec suggestions en temps réel',
    ],
    tags: ['Go', 'REST API', 'Geolocation', 'Leaflet', 'Maps', 'Geocoding'],
    category: 'CLI & Outils',
  },

  // ───── Nouveaux projets ─────

  // DevOps & Cloud
  {
    slug: 'play-with-containers',
    title: 'Play With Containers',
    repo: 'play-with-containers',
    lang: 'Docker',
    description: 'Exercices pratiques de conteneurisation Docker : multi-stage builds, networking, volumes et orchestration.',
    longDescription: 'Série d\'exercices avancés autour de Docker et de la conteneurisation. Le projet couvre les multi-stage builds pour optimiser la taille des images, le networking entre conteneurs, la gestion des volumes persistants et l\'orchestration avec Docker Compose. Chaque exercice met en pratique un concept clé de la conteneurisation en conditions réelles.',
    features: [
      'Multi-stage builds pour des images Docker optimisées',
      'Networking inter-conteneurs avec bridges et overlays',
      'Gestion de volumes pour la persistance des données',
      'Orchestration multi-services avec Docker Compose',
      'Bonnes pratiques de sécurité et de performance Docker',
    ],
    tags: ['Docker', 'Containers', 'Networking', 'Volumes', 'DevOps'],
    category: 'DevOps & Cloud',
  },

  // Systèmes & Réseau — Rust
  {
    slug: 'filler',
    title: 'Filler',
    repo: 'filler',
    lang: 'Rust',
    description: 'Jeu de stratégie IA : algorithme de placement optimal sur grille avec adversaire en temps réel.',
    longDescription: 'Implémentation d\'un bot IA pour le jeu Filler, un jeu de stratégie sur grille où deux joueurs placent des pièces à tour de rôle. Le bot analyse la grille en temps réel, évalue les positions selon une heuristique basée sur la distance à l\'adversaire et la maximisation du territoire. L\'algorithme utilise un flood fill optimisé pour le calcul des zones de contrôle.',
    features: [
      'Algorithme de placement basé sur des heuristiques de distance',
      'Flood fill optimisé pour le calcul de territoire',
      'Communication inter-processus via stdin/stdout',
      'Analyse en temps réel de la grille de jeu',
      'Stratégie adaptative selon le comportement adverse',
    ],
    tags: ['Rust', 'AI', 'Strategy', 'Algorithm', 'Game'],
    category: 'Systèmes & Réseau',
  },

  // Web & Backend — Go
  {
    slug: 'forum',
    title: 'Forum',
    repo: 'forum',
    lang: 'Go',
    description: 'Forum web complet en Go avec posts, commentaires, likes/dislikes et catégories.',
    longDescription: 'Application web de forum développée en Go pur avec SQLite comme base de données. Le projet implémente un système complet de posts avec catégories, commentaires imbriqués, likes et dislikes. L\'authentification par session sécurisée, le templating Go et la gestion des erreurs HTTP sont au cœur du projet. L\'architecture suit le pattern MVC adapté à Go.',
    features: [
      'Système de posts avec catégories et filtres',
      'Commentaires imbriqués avec likes/dislikes',
      'Authentification par session avec cookies sécurisés',
      'Templating serveur avec html/template',
      'Architecture MVC avec séparation des responsabilités',
    ],
    tags: ['Go', 'SQLite', 'MVC', 'Sessions', 'Web'],
    category: 'Web & Backend',
  },
  {
    slug: 'forum-image-upload',
    title: 'Forum Image Upload',
    repo: 'forum-image-upload',
    lang: 'Go',
    description: 'Extension de forum avec upload d\'images sécurisé, validation MIME et stockage optimisé.',
    longDescription: 'Module d\'upload d\'images pour application web Go. Le projet gère le cycle complet : validation du type MIME, limitation de taille, redimensionnement optionnel, stockage sur le serveur et serving des fichiers statiques. Les protections incluent la vérification des magic bytes pour éviter l\'upload de fichiers malveillants déguisés en images.',
    features: [
      'Upload sécurisé avec validation MIME et magic bytes',
      'Limitation de taille et de type de fichier',
      'Stockage serveur avec nommage unique (UUID)',
      'Serving optimisé des fichiers statiques',
      'Intégration dans les posts et commentaires du forum',
    ],
    tags: ['Go', 'Upload', 'Security', 'MIME', 'Web'],
    category: 'Web & Backend',
  },

  // Frontend & JavaScript
  {
    slug: 'graphql',
    title: 'GraphQL Explorer',
    repo: 'graphql',
    lang: 'JavaScript',
    description: 'Interface de visualisation de données via API GraphQL avec requêtes dynamiques et graphiques interactifs.',
    longDescription: 'Application front-end consommant une API GraphQL pour explorer et visualiser des données. Le projet implémente un client GraphQL avec construction dynamique de requêtes, pagination et cache. Les données sont rendues sous forme de graphiques interactifs (barres, lignes, secteurs) pour une exploration visuelle intuitive des datasets.',
    features: [
      'Client GraphQL avec requêtes dynamiques',
      'Visualisation de données avec graphiques interactifs',
      'Pagination et chargement incrémental des résultats',
      'Cache côté client pour les requêtes fréquentes',
      'Interface responsive de type dashboard',
    ],
    tags: ['JavaScript', 'GraphQL', 'Data Viz', 'Charts', 'API'],
    category: 'Frontend & JS',
  },

  // CLI & Outils — Go
  {
    slug: 'go-reloaded',
    title: 'Go Reloaded',
    repo: 'go-reloaded',
    lang: 'Go',
    description: 'Outil de transformation de texte avancé : corrections grammaticales, conversions et formatage automatique.',
    longDescription: 'Programme de traitement et transformation de texte en Go. L\'outil lit un fichier texte et applique des modifications basées sur des marqueurs : conversion hexadécimale/binaire en décimal, mise en majuscules/minuscules, correction de la ponctuation, gestion des articles (a/an) et formatage des guillemets. Le parsing utilise des expressions régulières et un système de remplacement contextuel.',
    features: [
      'Conversion hex/binaire/décimal dans le texte',
      'Corrections grammaticales automatiques (a/an, ponctuation)',
      'Mise en majuscules/minuscules contextuelles',
      'Formatage des guillemets et de la ponctuation',
      'Traitement de fichiers avec entrée/sortie configurable',
    ],
    tags: ['Go', 'Text Processing', 'Regex', 'CLI', 'Parser'],
    category: 'CLI & Outils',
  },
  {
    slug: 'math-skills',
    title: 'Math Skills',
    repo: 'math-skills',
    lang: 'Go',
    description: 'Outil statistique CLI calculant moyenne, médiane, variance et écart-type sur des datasets.',
    longDescription: 'Programme en ligne de commande pour l\'analyse statistique de données numériques. L\'outil lit un fichier de nombres et calcule les statistiques descriptives : moyenne, médiane, variance et écart-type. Développé en Go avec une attention à la précision numérique et à la gestion des cas limites (fichiers vides, nombres négatifs, grands datasets).',
    features: [
      'Calcul de moyenne, médiane, variance et écart-type',
      'Lecture de fichiers de données numériques',
      'Gestion des cas limites et erreurs de parsing',
      'Précision numérique avec arrondis contrôlés',
      'Output formaté pour intégration dans des pipelines',
    ],
    tags: ['Go', 'Statistics', 'Math', 'CLI', 'Data'],
    category: 'CLI & Outils',
  },
  {
    slug: 'ascii-art-color',
    title: 'ASCII Art Color',
    repo: 'ascii-art-color',
    lang: 'Go',
    description: 'Générateur ASCII art avec support des couleurs ANSI et mise en forme avancée du terminal.',
    longDescription: 'Extension du générateur ASCII art ajoutant le support complet des couleurs ANSI. Le programme permet de coloriser le texte ASCII généré avec des codes ANSI 8/16/256 couleurs, d\'appliquer des couleurs à des sous-chaînes spécifiques et de combiner différentes polices avec des couleurs. Compatible avec tous les terminaux supportant les séquences d\'échappement ANSI.',
    features: [
      'Support des couleurs ANSI 8, 16 et 256 couleurs',
      'Coloration sélective de sous-chaînes',
      'Combinaison polices ASCII + couleurs',
      'Compatibilité multi-terminal',
      'Flags CLI pour couleur, police et texte cible',
    ],
    tags: ['Go', 'ANSI', 'CLI', 'Terminal', 'ASCII Art'],
    category: 'CLI & Outils',
  },
  {
    slug: 'ascii-art-output',
    title: 'ASCII Art Output',
    repo: 'ascii-art-output',
    lang: 'Go',
    description: 'Exportation d\'ASCII art vers fichiers avec gestion multi-formats et redirections.',
    longDescription: 'Extension du générateur ASCII art permettant l\'exportation vers des fichiers. Le programme redirige la sortie ASCII vers des fichiers texte avec gestion des formats, préservation de l\'alignement et des retours à la ligne. Utile pour générer des banners, des signatures et des headers pour des fichiers de configuration ou de documentation.',
    features: [
      'Exportation vers fichiers texte avec flag --output',
      'Préservation de l\'alignement et du formatage',
      'Support de multiples polices ASCII',
      'Intégration avec pipes et redirections Unix',
      'Gestion des erreurs d\'écriture et permissions',
    ],
    tags: ['Go', 'CLI', 'File I/O', 'ASCII Art', 'Unix'],
    category: 'CLI & Outils',
  },
  {
    slug: 'ascii-art-fs',
    title: 'ASCII Art FS',
    repo: 'ascii-art-fs',
    lang: 'Go',
    description: 'Sélection de polices ASCII art via système de fichiers avec chargement dynamique de banners.',
    longDescription: 'Extension du générateur ASCII art avec un système de fichiers de polices. Le programme charge dynamiquement les fichiers de polices (standard, shadow, thinkertoy) depuis le système de fichiers, avec validation de l\'intégrité des fichiers de banner. Le sélecteur de police permet de mixer les styles et de créer des rendus typographiques variés.',
    features: [
      'Chargement dynamique de polices depuis le filesystem',
      'Validation d\'intégrité des fichiers de banner',
      'Support des polices standard, shadow et thinkertoy',
      'Flag CLI pour la sélection de police',
      'Gestion d\'erreurs pour fichiers manquants ou corrompus',
    ],
    tags: ['Go', 'CLI', 'File System', 'ASCII Art', 'Fonts'],
    category: 'CLI & Outils',
  },
  {
    slug: 'ascii-art-justify',
    title: 'ASCII Art Justify',
    repo: 'ascii-art-justify',
    lang: 'Go',
    description: 'Alignement et justification d\'ASCII art : centré, gauche, droite et justifié selon la largeur du terminal.',
    longDescription: 'Extension du générateur ASCII art ajoutant l\'alignement et la justification du texte. Le programme détecte la largeur du terminal et aligne le texte ASCII généré : gauche, droite, centré ou justifié. L\'algorithme de justification distribue les espaces de manière uniforme entre les mots pour remplir la largeur disponible.',
    features: [
      'Alignement gauche, droite, centré et justifié',
      'Détection automatique de la largeur du terminal',
      'Distribution uniforme des espaces pour la justification',
      'Compatible avec toutes les polices ASCII',
      'Flag --align pour le choix de l\'alignement',
    ],
    tags: ['Go', 'CLI', 'Terminal', 'ASCII Art', 'Typography'],
    category: 'CLI & Outils',
  },
  {
    slug: 'groupie-tracker-search-bar',
    title: 'Groupie Tracker Search',
    repo: 'groupie-tracker-search-bar',
    lang: 'Go',
    description: 'Barre de recherche autocomplete pour tracker de concerts avec suggestions temps réel.',
    longDescription: 'Extension du projet Groupie Tracker ajoutant une barre de recherche avec autocomplétion. Le système indexe les noms d\'artistes, les lieux de concerts et les dates pour fournir des suggestions en temps réel pendant la saisie. L\'algorithme de recherche utilise le tri-gram matching pour tolérer les fautes de frappe et les recherches partielles.',
    features: [
      'Autocomplétion temps réel pendant la saisie',
      'Recherche multi-critères (artiste, lieu, date)',
      'Tri-gram matching pour tolérance aux fautes de frappe',
      'Indexation côté serveur des données de concerts',
      'Interface de suggestions avec navigation clavier',
    ],
    tags: ['Go', 'Search', 'Autocomplete', 'API', 'Web'],
    category: 'Web & Backend',
  },
  {
    slug: 'groupie-tracker-visualizations',
    title: 'Groupie Tracker Viz',
    repo: 'groupie-tracker-visualizations',
    lang: 'Go',
    description: 'Visualisation de données de concerts avec graphiques interactifs et statistiques d\'artistes.',
    longDescription: 'Extension du projet Groupie Tracker ajoutant des visualisations de données. Le projet transforme les données brutes de concerts en graphiques interactifs : timeline des concerts par année, répartition géographique, statistiques par genre musical. Le rendu utilise des templates Go enrichis de composants JavaScript pour l\'interactivité des charts.',
    features: [
      'Timeline interactive des concerts par année',
      'Répartition géographique des événements',
      'Statistiques par genre musical et par artiste',
      'Graphiques interactifs avec JavaScript',
      'Templates Go pour le rendu serveur',
    ],
    tags: ['Go', 'Data Viz', 'Charts', 'API', 'Web'],
    category: 'Web & Backend',
  },
  {
    slug: 'groupie-tracker-filters',
    title: 'Groupie Tracker Filters',
    repo: 'groupie-tracker-filters',
    lang: 'Go',
    description: 'Système de filtres avancés pour tracker de concerts : plage de dates, lieux et nombre de membres.',
    longDescription: 'Extension du projet Groupie Tracker avec un système de filtrage multi-critères. Les utilisateurs peuvent combiner des filtres par plage de dates de création, nombre de membres du groupe, localisation des concerts et date du premier album. Le backend applique les filtres côté serveur avec un système de query builder dynamique.',
    features: [
      'Filtres combinables par date, lieu et taille du groupe',
      'Range sliders pour les filtres numériques',
      'Checkboxes pour les filtres catégoriels',
      'Query builder dynamique côté serveur',
      'URL state pour partager les filtres appliqués',
    ],
    tags: ['Go', 'Filters', 'Query Builder', 'API', 'Web'],
    category: 'Web & Backend',
  },
  {
    slug: 'crud-master',
    title: 'CRUD Master',
    repo: 'crud-master',
    lang: 'Python',
    description: 'Application CRUD complète avec API REST, base de données relationnelle et interface d\'administration.',
    longDescription: 'Projet d\'application CRUD (Create, Read, Update, Delete) complète développé en Python. L\'application expose une API REST pour la gestion de ressources avec validation des données, pagination et tri. Le backend gère les opérations CRUD sur une base de données relationnelle avec un ORM et propose une interface d\'administration pour la gestion des entités.',
    features: [
      'API REST complète avec toutes les opérations CRUD',
      'Validation des données en entrée et sortie',
      'Pagination, tri et recherche sur les listes',
      'Interface d\'administration web',
      'Tests automatisés des endpoints API',
    ],
    tags: ['Python', 'REST API', 'CRUD', 'Database', 'ORM'],
    category: 'DevOps & Cloud',
  },

  // ───── Apps & SaaS (projets privés / professionnels) ─────
  {
    slug: 'ecampus',
    title: 'eCampus',
    repo: 'eCampus',
    lang: 'Go',
    description: 'Plateforme de campus virtuel multi-tenant — microservices Go, classes virtuelles LiveKit, IA conversationnelle et mobile money. En production sur ecampus-sn.com.',
    longDescription: 'eCampus unifie en une seule expérience numérique tout ce qui fait la vie d\'un établissement africain : cours, devoirs, classes virtuelles, notes, bulletins LMD, finances, communication, vie scolaire. L\'architecture repose sur 22+ microservices Go (un par domaine, base PostgreSQL dédiée), trois clients (web Next.js 16, panel admin Next.js, app mobile Expo) et un assistant IA conversationnel (Amigo) branché sur Claude ou Gemini avec function calling. Multi-tenant strict via JWT (X-User-Institution propagé à tous les services), classes virtuelles LiveKit avec replay automatique via Egress, paiement mobile money intégré (Wave, Orange Money, MTN, Free Money). Conçu pour fonctionner en contexte africain : 3G, smartphones d\'entrée de gamme, mode dégradé.',
    features: [
      '22+ microservices Go avec NATS JetStream et observabilité OpenTelemetry/Jaeger',
      'Classes virtuelles LiveKit + Egress pour replay MP4 automatique',
      'Amigo — assistant IA conversationnel (Claude/Gemini) avec function calling rôle-aware',
      'Multi-tenant par institution (UCAD, UGB) — isolation systématique sameTenant()',
      'Mobile money sénégalais (Wave, Orange Money, MTN MoMo, Free Money) + factures',
    ],
    tags: ['Go', 'Next.js', 'Expo', 'PostgreSQL', 'NATS', 'LiveKit', 'Multi-tenant', 'Mobile Money', 'AI Agent'],
    category: 'Apps & SaaS',
    private: true,
    liveUrl: 'https://ecampus-sn.com',
  },
  {
    slug: 'pharmos',
    title: 'PharmOS',
    repo: 'pharmos',
    lang: 'Go',
    description: 'Plateforme logicielle complète pour officines pharmaceutiques au Sénégal et en zone UEMOA — POS cloud-first, traçabilité GS1, tiers payant CMU/IPM, comptabilité SYSCOHADA.',
    longDescription: 'PharmOS est une plateforme métier qui ambitionne de devenir le système d\'exploitation par défaut des officines en Afrique francophone. Le produit remplace le papier et Excel par un POS cloud-first multilingue (français + wolof), intègre nativement la sérialisation GS1 et la lutte contre les médicaments contrefaits, automatise le tiers payant CMU/IPM/mutuelles en temps réel, gère la comptabilité SYSCOHADA conforme OHADA de bout en bout (sans dépendance à Sage/Ciel) et fonctionne en mode dégradé pour les officines sans réseau (synchro différée). L\'architecture est un monolithe modulaire Go découpé en modules métier isolés (identity, catalog, stock FEFO, POS, accounting, regulatory, patient, coverage, payments) communiquant par événements via NATS JetStream avec outbox transactionnel. App desktop packagée via Tauri pour fonctionnement local.',
    features: [
      'Monolithe modulaire Go — 9 modules métier (POS, stock FEFO, comptabilité SYSCOHADA, etc.)',
      'Outbox transactionnel + NATS JetStream avec mode dégradé si NATS down',
      'Multi-officines (row-level scoping) — un user multi-membership avec rôle distinct par officine',
      'Traçabilité GS1 datamatrix + registre stupéfiants + pharmacovigilance',
      'Tiers payant CMU/IPM + mobile money (Wave, Orange Money, Free Money) — intentions QR/USSD',
    ],
    tags: ['Go', 'PostgreSQL', 'NATS', 'Tauri', 'React', 'Multi-tenant', 'SYSCOHADA', 'GS1', 'Mobile Money'],
    category: 'Apps & SaaS',
    private: true,
  },
  {
    slug: 'souhibou-telecom',
    title: 'Souhibou Télécom',
    repo: 'st-web-app',
    lang: 'TypeScript',
    description: 'Écosystème e-commerce high-tech — plateforme Next.js, dashboard CRM admin et app mobile, API Go, paiement CinetPay.',
    longDescription: 'Écosystème e-commerce complet pour la vente de produits high-tech (téléphones, télévisions, tablettes, accessoires) au Sénégal. Le projet se compose de trois piliers : une plateforme e-commerce Next.js (catalogue, panier, checkout, espace client, live chat), un dashboard CRM admin (gestion produits, commandes, coupons, flash sales, avis, utilisateurs, analytics) et une application mobile. Le backend API Go (architecture clean cmd/internal/pkg) gère le paiement CinetPay, les factures, les livraisons, le programme de fidélité et les notifications SMS.',
    features: [
      'Plateforme e-commerce avec catalogue, panier, wishlist et checkout',
      'Dashboard CRM admin : produits, commandes, coupons, flash sales, users, analytics',
      'Application mobile pour l\'expérience client',
      'Backend Go avec paiement CinetPay, factures, livraison et fidélité',
      'Notifications SMS, live chat et système d\'avis clients',
    ],
    tags: ['Next.js', 'Go', 'CinetPay', 'E-commerce', 'CRM', 'Mobile'],
    category: 'Apps & SaaS',
    private: true,
  },
  {
    slug: 'levelofficiel',
    title: 'Level Officiel',
    repo: 'levelofficiel',
    lang: 'Vue',
    description: 'Boutique e-commerce hijab avec WooNuxt, paiement Stripe et gestion de catalogue produits.',
    longDescription: 'Site e-commerce pour une marque de hijab développé avec WooNuxt (Nuxt + WooCommerce headless). La boutique intègre un catalogue produits avec filtres et variations, un panier temps réel, le paiement sécurisé via Stripe et une gestion des commandes. L\'architecture headless sépare le frontend Vue/Nuxt du backend WordPress/WooCommerce pour des performances optimales.',
    features: [
      'Catalogue produits avec filtres, tailles et variantes',
      'Panier et checkout avec paiement Stripe intégré',
      'Architecture headless WooNuxt (Nuxt + WooCommerce)',
      'Animations et transitions fluides avec VueUse Motion',
      'Interface responsive optimisée mobile-first',
    ],
    tags: ['Nuxt', 'Vue', 'WooCommerce', 'Stripe', 'E-commerce'],
    category: 'Apps & SaaS',
    private: true,
  },
  {
    slug: 'jamah-pikine',
    title: 'Jamah Pikine',
    repo: 'fityanusidqinepikine',
    lang: 'Vue',
    description: 'Écosystème communautaire religieux — plateforme web, dashboard admin, apps mobiles (React Native + Capacitor), streaming et téléchargement de Zikr.',
    longDescription: 'Écosystème multiplateforme complet pour la communauté Fityanu Sidqine de Pikine. Le projet se compose de trois piliers : une plateforme web Nuxt (bibliothèque audio de Zikr avec écoute et téléchargement, cours/dars, galerie, wird tidiane, doua), un dashboard admin (gestion audio, membres, contributions, fonds, broadcasts, publicités) et deux applications mobiles (React Native/Expo + Android Capacitor). Le lecteur audio global permet le streaming continu avec favoris. Le backend Supabase gère l\'auth, la base de données et le stockage, avec AWS S3 pour les médias et des visualisations 3D (Three.js, Spline, Globe).',
    features: [
      'Bibliothèque de Zikr avec écoute streaming et téléchargement',
      'Dashboard admin : gestion audio, membres, contributions, fonds et broadcasts',
      'Apps mobiles React Native (iOS/Android) + Nuxt/Capacitor (Android)',
      'Lecteur audio global avec favoris et lecture continue',
      'Backend Supabase + stockage S3, visualisations 3D, génération PDF',
    ],
    tags: ['Nuxt', 'React Native', 'Capacitor', 'Supabase', 'S3', 'Audio'],
    category: 'Apps & SaaS',
    private: true,
  },
  {
    slug: 'vortex',
    title: 'Vortex Agency',
    repo: 'vortex',
    lang: 'Vue',
    description: 'Site vitrine d\'agence digitale — Nuxt, animations 3D Three.js/Spline, effets visuels et motion design.',
    longDescription: 'Site vitrine premium pour une agence de solutions digitales, développé avec Nuxt 3. Le site se distingue par ses animations et effets visuels avancés : globe 3D interactif (Three.js/Cobe), scènes Spline intégrées, animations GSAP et Lenis smooth scroll, effets de postprocessing et noise textures. L\'architecture utilise shadcn-vue pour les composants UI et Zod pour la validation des formulaires.',
    features: [
      'Globe 3D interactif et scènes Spline embarquées',
      'Animations avancées GSAP + Lenis smooth scroll',
      'Composants UI shadcn-vue avec Radix Vue',
      'Effets visuels : postprocessing, simplex noise, confetti',
      'SEO optimisé avec Nuxt Scripts et Google Analytics',
    ],
    tags: ['Nuxt', 'Three.js', 'Spline', 'GSAP', 'shadcn', 'Motion'],
    category: 'Apps & SaaS',
    private: true,
  },
  {
    slug: 'fsp-mobile',
    title: 'FSP Mobile',
    repo: 'fsp-react-native',
    lang: 'TypeScript',
    description: 'App mobile React Native/Expo de l\'écosystème Jamah Pikine — Zikr audio, horaires de prière, géolocalisation et offline-first.',
    longDescription: 'Application mobile communautaire développée en React Native avec Expo. L\'app intègre les horaires de prière (librairie Adhan) avec géolocalisation, un lecteur audio avancé (React Native Track Player) pour les cours et conférences, le stockage offline avec SQLite et Expo SecureStore, les notifications push et la synchronisation Supabase. L\'interface utilise NativeWind (Tailwind pour RN) et Reanimated pour les animations natives.',
    features: [
      'Horaires de prière avec calcul astronomique (Adhan) et GPS',
      'Lecteur audio/vidéo avancé avec React Native Track Player',
      'Mode offline-first avec SQLite et synchronisation Supabase',
      'Notifications push et mises à jour OTA (Expo Updates)',
      'Animations natives fluides avec Reanimated et Gesture Handler',
    ],
    tags: ['React Native', 'Expo', 'Supabase', 'NativeWind', 'SQLite'],
    category: 'Apps & SaaS',
    private: true,
  },
  {
    slug: 'fsp-mobile-android',
    title: 'FSP Mobile Android',
    repo: 'fsp-mobile-android',
    lang: 'Vue',
    description: 'Version Android de l\'écosystème Jamah Pikine — Nuxt + Capacitor, Zikr audio, SQLite, push notifications et S3.',
    longDescription: 'Version Android de l\'application communautaire FSP, construite avec Nuxt et packagée nativement via Capacitor. L\'app combine le rendu web Nuxt avec les APIs natives Android : SQLite pour le stockage local, push notifications Firebase, accès au filesystem et partage natif. Le contenu est synchronisé avec Supabase et les médias stockés sur AWS S3 avec URLs présignées.',
    features: [
      'Application Android native via Nuxt + Capacitor',
      'SQLite local avec synchronisation Supabase',
      'Push notifications Firebase Cloud Messaging',
      'Génération et ouverture de PDF natifs (jsPDF)',
      'Stockage médias AWS S3 avec URLs présignées',
    ],
    tags: ['Nuxt', 'Capacitor', 'Android', 'Firebase', 'Supabase', 'S3'],
    category: 'Apps & SaaS',
    private: true,
  },
]

export const CATEGORIES = [
  { label: 'Tous' as const, icon: 'material-symbols:grid-view' },
  { label: 'Apps & SaaS' as Category, icon: 'material-symbols:rocket-launch' },
  { label: 'Sécurité & IA' as Category, icon: 'material-symbols:security' },
  { label: 'DevOps & Cloud' as Category, icon: 'material-symbols:cloud' },
  { label: 'Systèmes & Réseau' as Category, icon: 'mdi:language-rust' },
  { label: 'Web & Backend' as Category, icon: 'file-icons:go' },
  { label: 'Frontend & JS' as Category, icon: 'mdi:language-javascript' },
  { label: 'CLI & Outils' as Category, icon: 'material-symbols:terminal' },
]

export function useLangColor(lang: string): string {
  const map: Record<string, string> = {
    Go: 'bg-sky-100 text-sky-700',
    Rust: 'bg-orange-100 text-orange-700',
    TypeScript: 'bg-blue-100 text-blue-700',
    JavaScript: 'bg-yellow-100 text-yellow-700',
    Python: 'bg-green-100 text-green-700',
    Terraform: 'bg-purple-100 text-purple-700',
    Makefile: 'bg-slate-100 text-slate-600',
    Docker: 'bg-cyan-100 text-cyan-700',
    Vue: 'bg-emerald-100 text-emerald-700',
  }
  return map[lang] ?? 'bg-slate-100 text-slate-600'
}

export function useCategoryIcon(cat: string): string {
  const map: Record<string, string> = {
    'Sécurité & IA': 'material-symbols:security',
    'DevOps & Cloud': 'material-symbols:cloud',
    'Systèmes & Réseau': 'mdi:language-rust',
    'Web & Backend': 'file-icons:go',
    'Frontend & JS': 'mdi:language-javascript',
    'CLI & Outils': 'material-symbols:terminal',
    'Apps & SaaS': 'material-symbols:rocket-launch',
  }
  return map[cat] ?? 'uil:github'
}

export function useCategoryAccent(cat: string): string {
  const map: Record<string, string> = {
    'Sécurité & IA': 'bg-red-50 text-red-600',
    'DevOps & Cloud': 'bg-purple-50 text-purple-600',
    'Systèmes & Réseau': 'bg-orange-50 text-orange-600',
    'Web & Backend': 'bg-sky-50 text-sky-600',
    'Frontend & JS': 'bg-yellow-50 text-yellow-600',
    'CLI & Outils': 'bg-slate-100 text-slate-600',
    'Apps & SaaS': 'bg-emerald-50 text-emerald-600',
  }
  return map[cat] ?? 'bg-slate-100 text-slate-600'
}
